[tool.poetry]
name = "realtime"
version = "1.0.0"
description = ""
authors = ["Joel"]

[tool.poetry.dependencies]
python = "^3.8"
websockets = ">=10.3"
python-dateutil = "^2.8.1"
typing-extensions = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
